name: "MplabX XC32 v2.41 with legacy plib "
description: "This action builds an MPLABX/xc32 with legacy libraries project in a Linux container."
branding:
  icon: package
  color: blue

inputs:
  project:
    description: Project folder location
    required: true
  configuration:
    description: Configuration to build
    required: true
    default: "default"

runs:
  using: "docker"
  image: "docker://ghcr.io/pbrunot/ghactions-mplabx-xc32-plib:latest"
  args:
    - ${{ inputs.project }}
    - ${{ inputs.configuration }}
